### PR TITLE
use unresolved hostname in single node settings

### PR DESCRIPTION
**Pull request by wuan**
When adding this, the host name used in single node settings is resolved again if there is a connection failure.

### CODE REVIEW

**Comment by dpolivaev** [comment]
I would like to explain why this pull request is really important: we want to use automatically recovered event store instances and load balancers using AWS auto scaling groups to restart them in case of failure. We learned that the AWS load balancer IP addresses change over the time.  So the proposed fix was needed to use single node event store with changing IP address. 
Certainly, the problem could also be solved by using DNS and event store cluster, but we have not implemented it yet.
Could you merge the pull request?

**Comment by wuan** [comment]
We would like to add this minimal feature as it is the basis for using multiple eventstore instances behind a load balancer. We are thinking about a specific client for that purpose, where the loadbalancer is used to get accesss to the cluster's gossip information which should be used by the client. What do you think about it?

**Comment by msemys** [comment]
there is another address setter method in eventstore builder, that could be useful in this case:

https://github.com/msemys/esjc/blob/master/src/main/java/com/github/msemys/esjc/EventStoreBuilder.java#L134

e.g.: 
```java 
EventStoreBuilder.newBuilder()
    .singleNodeAddress(InetSocketAddress.createUnresolved(host, port))
```

**Comment by dpolivaev** [comment]
Thank you very much for your comment, it helps.

**Comment by wuan** [comment]
Thanks, that is what we need!

**Pull request closed without merging**
